[package]
name = "thorium"
description = "Lokathor-does-stuff-ium"
repository = "https://github.com/Lokathor/thorium"
version = "0.0.0"
edition = "2021"
license = "Zlib OR Apache-2.0 OR MIT"

[dependencies]
lazy_static = "1.4.0"
