[package]
name = "thorium"
description = "Lokathor-does-stuff-ium"
repository = "https://github.com/Lokathor/thorium"
version = "0.5.0"
edition = "2021"
license = "Zlib OR Apache-2.0 OR MIT"

[dependencies]
beryllium = "0.13.0"
fermium = "22605.0.0"
yacurses = "0.2.4"
